// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdqsqIRTetN1jnEGon-_X7shqkADEXqRI',
    appId: '1:858532355473:web:3417689dfc73bd97780e30',
    messagingSenderId: '858532355473',
    projectId: 'flutter-learn-mmh',
    authDomain: 'flutter-learn-mmh.firebaseapp.com',
    storageBucket: 'flutter-learn-mmh.firebasestorage.app',
    measurementId: 'G-4JS6FJ2CCB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyeXxWkTsauSjabW56-GmNk120qHlBo_4',
    appId: '1:858532355473:android:88e43ed1a577d8b8780e30',
    messagingSenderId: '858532355473',
    projectId: 'flutter-learn-mmh',
    storageBucket: 'flutter-learn-mmh.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCy6nWzXe-3NfHNvQXRrYy8epjVQrYmsaY',
    appId: '1:858532355473:ios:a0d1e3e2d8953d69780e30',
    messagingSenderId: '858532355473',
    projectId: 'flutter-learn-mmh',
    storageBucket: 'flutter-learn-mmh.firebasestorage.app',
    iosBundleId: 'com.example.flutterLearning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCy6nWzXe-3NfHNvQXRrYy8epjVQrYmsaY',
    appId: '1:858532355473:ios:a0d1e3e2d8953d69780e30',
    messagingSenderId: '858532355473',
    projectId: 'flutter-learn-mmh',
    storageBucket: 'flutter-learn-mmh.firebasestorage.app',
    iosBundleId: 'com.example.flutterLearning',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdqsqIRTetN1jnEGon-_X7shqkADEXqRI',
    appId: '1:858532355473:web:ace9129afe3fb6a1780e30',
    messagingSenderId: '858532355473',
    projectId: 'flutter-learn-mmh',
    authDomain: 'flutter-learn-mmh.firebaseapp.com',
    storageBucket: 'flutter-learn-mmh.firebasestorage.app',
    measurementId: 'G-YGBFX8Y2XV',
  );
}
